### ISSUE TITLE
How does this compare to logzero?

### ISSUE THREAD

**Issue by dseptem** [jd/daiquiri#13]
http://logzero.readthedocs.io/

Great work, by the way.

**Comment by jd** [comment]
They seem to overlap a bit, though logzero seems a bit more file oriented in its API, whereas daiquiri is more generic. I'd say daiquiri has less opinion about where and how you should log.
It also do not try to interfere with the Python logging subsystem whereas logzero seems (from my quick skimming through the code) try to encode/decode string/bytes.
