### ISSUE TITLE
Daiquiri removes all handlers

### ISSUE THREAD

**Issue by asyncee** [jd/daiquiri#21]
Hello, the library removes all existing handlers, and that is causing conflicts with third-party libraries, for example [click](http://click.pocoo.org/6/).

When click application is started, i setup logging, and if there are any exceptions in an application, then it just shutdowns silently, because it can not report about crash.

**Comment by jd** [comment]
Not sure I understand exactly what your problem is. Can you provide a snippet that shows what you have and what you'd like instead?

**Comment by asyncee** [comment]
I'm talking about 'setup' function: [daiquiri/__init__.py](https://github.com/jd/daiquiri/blob/master/daiquiri/__init__.py#L86)

There are a block of code to remove all previously configured handler, as per:

```  
    # Remove all handlers
    for handler in list(root_logger.handlers):
        root_logger.removeHandler(handler)
```

So, when i start application, it configures some logging handlers, which then deleted by daiquiri.

Maybe add `remove_handlers=True` keyword argument to the `setup` function?

**Comment by jd** [comment]
Why don't you call `daiquiri.setup` first?

**Comment by asyncee** [comment]
Because there are other software that takes responsibility to pre-configure logging itself, like daiquiri does. In this situations there are conflict.

Actually, i do not insist, just want to help you improve you library. :)

I'll close the issue, because i  have chosen other solution, that fits my needs. Have a nice day!

**Comment by jd** [comment]
> Because there are other software that takes responsibility to pre-configure logging itself, like daiquiri does. In this situations there are conflict.

Ah, that's interesting. Do you have any example of one of those?

**Comment by asyncee** [comment]
I have experienced it with click + flask, but right now i have no code samples, sorry.

Just imagine, if i want to start application with --debug flag, which enables debug level loggers, for example, and info otherwise.

First of all i need to import other libraries and let them read console arguments and interpret it.
At this moment this libraries may configure logging internally. And after that, i would call daiquiri.setup() -> not on module level, but in function.

**Comment by jd** [comment]
Click does not do any logging configuration as far as I saw.

> this libraries may configure logging internally

Ok, then just call daiquiri first :)
