### ISSUE TITLE
Logging to journal with a key/value is broken

### ISSUE THREAD

**Issue by paravoid** [jd/daiquiri#44]
I'm not sure if I'm doing something wrong, but the following two piece of code generate a exception. I tested versions 1.5.0, 1.6.0 and then 2.1.0 in a clean venv.

```python
daiquiri.setup(level=logging.INFO, outputs=("stdout", "journal"))
logger = daiquiri.getLogger("test", FOO="bar")
logger.info("it works")
```

```python
daiquiri.setup(level=logging.INFO, outputs=("stdout", "journal"))
logger = daiquiri.getLogger("test")
logger.info("it works", FOO="bar")
```

The backtrace results in line 92, in emit:
```python
    for k, v in record._daiquiri_extra_keys:
ValueError: too many values to unpack (expected 2)
```

From what I could see, `record._daiquiri_extra_keys` was just a tuple of "FOO", without a value, so not sure what's going on there.

**Comment by jd** [comment]
Can you give a try at #45 I think it should fix it.
